### ISSUE TITLE
Mejoras generales

### ISSUE THREAD

**Issue by BoscoDomingo** [MS-ES-DEMO/avd-fast-deploy#3]
deploy.CLI.ps1 está mal. Los cambios son:

- `SecureString` para adminPassword (opcional)
- `az deployment sub create -l westeurope -n $deploymentName --template-file $templateFile --parameters $parameterFile --parameters $params`

`avdConfiguration` necesita un objeto `profiles` que no está al desplegar en personal (pooled sí lo tiene):
![image](https://user-images.githubusercontent.com/46006784/148051195-01fbbe84-c8c2-4e6b-8d5f-3edef68cf746.png)

 
Hay que recordar el cambio del `diagnosticsStorageAccountName`

**Comment by mlrcloud** [comment]
Done
